name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies and build Client
        run: |
          cd Client
          npm install
          npm run build

      - name: Copy build output to Server directory
        run: |
          cp -r Client/dist Server/public

      - name: Clean .git from Server directory
        run: |
          rm -rf Server/.git*
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: Server
